### ISSUE TITLE
[Feature Request]: Option to Set Any Item ID as a Design

### ISSUE THREAD

**Issue by Feranogame** [Farcr/vanity#14]
The ability to set any item ID as a design would be a welcome way to allow pre-existing items and blocks with other uses as designs. Such a change would also allow for more custom coded blocks and items to be made available in Vanity Packs for those with coding knowledge. If paired with Custom Lore Strings (see Issue #13), this would not be that confusing to players as said items could have a "Can be used as a Design" tooltip, and may even be a welcome easter egg/surprise.

**Comment by ThatGravyBoat** [comment]
Added in 1.20.5 port using data components.
