### ISSUE TITLE
[Feature Request]: Individual Item IDs for Design Items

### ISSUE THREAD

**Issue by Feranogame** [Farcr/vanity#18]
With 1.20.5 coming and introducing many changes to items, as well as Neoforge overtaking Forge, I expect some mod code might need to be largely rewritten. With that in mind, I'd like to suggest making designs have their own item IDs.

Cons:
- Probably harder to code.

Pros:
- Fixes Designs appearing in JEI or other similar mods;
- Streamlines Design insertion into loot tables;
- Allows Designs to be individually tagged;
- Makes Designs more compatible with other modded systems which might not support checking NBT or 1.20.5+ components.

**Comment by ThatGravyBoat** [comment]
Added in 1.20.5 port using data components.
