### ISSUE TITLE
[Bug]: Crashes on startup

### ISSUE THREAD

**Issue by FlixFox** [Farcr/vanity#22]
### Bug Description

When trying to start a Minecraft modpack with this mod, MC crashes directly. I tried again with only this mod and otherwise completely vanilla, same result.

### Version

2.0.0

### Mod Loader Version

1.20.4 - 49.1.0

### Mod Loader

Forge

### Logs or additional context

![Fehler](https://github.com/user-attachments/assets/9230a09e-603c-4556-bdd4-809d72791ee3)

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
crashlog is required

**Comment by FlixFox** [comment]
Here is the Crashlog:
[crash-2024-12-05_01.06.55-client.txt](https://github.com/user-attachments/files/18015503/crash-2024-12-05_01.06.55-client.txt)
